sudo: required

services:
  - docker

language: node_js

node_js:
  - "8"

before_install:
  - curl "https://install.meteor.com/?release=1.6.1" | /bin/sh

script:
  - meteor --version
  - sh bucketful-build.sh
  - docker image ls

