sudo: required

services:
  - docker

language: node_js

node_js:
  - "8"

before_install:
  - curl "https://install.meteor.com/?release=1.6.1" | /bin/sh

script:
  - meteor --version
  - sh bucketful-build.sh
  - docker image ls

before_deploy:
  - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"

deploy:
  provider: script
  script: docker push beforetheend/bucketful:$TRAVIS_BRANCH
  script: if [ "$TRAVIS_BRANCH" = "master" ]; then docker push beforetheend/bucketful:latest; fi
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^codedeploy|dev|master$



