sudo: required

services:
  - docker

language: node_js

node_js:
  - "8"

cache:
  directories:
    - $HOME/docker

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'


before_install:
  - curl "https://install.meteor.com/?release=1.6.1" | /bin/sh
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

script:
  - docker image ls
  - meteor --version
  - sh bucketful-build.sh
  - docker image ls


before_deploy:
  - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
  - docker push beforetheend/bucketful:$TRAVIS_BRANCH

deploy:
  - provider: codedeploy
    revision_type: github
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    application: "Bucketful-App"
    deployment_group: $TRAVIS_BRANCH
    region: "us-east-1"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^dev|master$





