sudo: required

services:
  - docker

language: node_js

node_js:
  - "8"

before_install:
  - curl "https://install.meteor.com/?release=1.6.1" | /bin/sh

script:
  - ls -al /var/lib/
  - sudo ls -al /var/lib/
  - meteor --version
  - sh bucketful-build.sh
  - docker image ls


before_deploy:
  - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
  - docker push beforetheend/bucketful:$TRAVIS_BRANCH

deploy:
  - provider: codedeploy
    revision_type: github
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    application: "Bucketful-App"
    deployment_group: $TRAVIS_BRANCH
    region: "us-east-1"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^dev|master$





